### ISSUE TITLE
Game crashes with just 3 mods.

### ISSUE THREAD

**Issue by LIpeMiner** [MerchantPug/cursedorigins#2]
I wanted to see what the supposed secret origin added by the mod was, when I launched the game it simply crashed, with 3 mods,
Fabric Api, Origins (7.0) and CursedOrigins.
Forgot to mention that removing CursedOrigins made the game function properly and not crash.

**Comment by ChrysanthCow** [comment]
I'll check this out and I'll release a new version as soon as possible.
In future, please provide crash logs. (You can access them through a setting on the Minecraft launcher.) At least this was very easy to produce.

It has to do with changing the Respawn Anchor from my understanding, apologies for not checking this before release.

**Comment by ChrysanthCow** [comment]
Fixed in 1.1.1!
Thanks for bringing this to my attention, it must've sucked just downloading the mod and seeing the game crash.
