### ISSUE TITLE
server crashing after start

### ISSUE THREAD

**Issue by saltgurkor** [MerchantPug/cursedorigins#4]
[latest.log](https://github.com/MerchantPug/cursedorigins/files/6315981/latest.log)

[WinRAR ZIP archive.zip](https://github.com/MerchantPug/cursedorigins/files/6315986/WinRAR.ZIP.archive.zip)

**Comment by ChrysanthCow** [comment]
I've figured out exactly what's causing it. I'll be releasing a fix for this sometime soon.

I was using a clientside only method on the server when it doesn't exist

**Comment by ChrysanthCow** [comment]
I've fixed it and I will be closing this issue as soon as the patch it's been released in has happened.
