### ISSUE TITLE
Cant join own server 

### ISSUE THREAD

**Issue by GoldenMaster8** [MerchantPug/cursedorigins#5]
every time i try to join my own server, the error message 

"Refistry remapping failed: Received ID map for minecraft:mob_effect contains IDs unknown to the receiver!

- cursedorigins:charged"

i also have some other mods running, so it could also be them

**Comment by ChrysanthCow** [comment]
May I see your modlist and full logs?

Also make sure to check if the same version of CursedOrigins is both on the client and the server.

**Comment by GoldenMaster8** [comment]
im not sure about the logs but the modlist is

- Extra Alchemy
- Extra Origins
- Fabric API
- Mob Origins
- Origins
- Origins: Classes
- Pehkui
- Requiem
- REI
- Slime Origin
- Sodium

**Comment by ChrysanthCow** [comment]
I'll see if I can replicate this because I left this issue for too long.

I won't try now but I'll see if I can later.

**Comment by ChrysanthCow** [comment]
Closed due to inactivity.
